version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop-application
      timeout: 5
  ApplicationStart:
    - location: scripts/start-application
      timeout: 5
      runas: ubuntu
  ValidateService:
    - location: scripts/validate
      timeout: 5
