version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y nodejs build-essential
  pre_build:
    commands:
      - npm install
      - NODE_ENV=test node db.js
  build:
    commands:
      - node_modules/mocha/bin/mocha tests

artifacts:
  files:
    - '**/*'
